In [1]:
# use VnCoreNLP word segmentation
from vncorenlp import VnCoreNLP
annotator = VnCoreNLP("/home/phamson/VnCoreNLP/VnCoreNLP-1.1.1.jar", annotators="wseg", max_heap_size='-Xmx500m') 

In [2]:
import torch
import pandas as pd
import numpy as np
from tqdm import tqdm, trange
from transformers import AutoModel, AutoTokenizer, AutoModelForTokenClassification

# load phobert-ner đã được fine-tuned
phobert_ner = AutoModelForTokenClassification.from_pretrained("/home/phamson/bert-ner/real_estate_ner/")
# load tokenizer của phobert 
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base", use_fast=False)


# phobert = AutoModel.from_pretrained("vinai/phobert-base")


INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [9]:
# # tạo label list tương ứng với bộ dữ liệu
# label_list = [
#     "O",       # Outside of a named entity
#     "B-MISC",  # Beginning of a miscellaneous entity right after another miscellaneous entity
#     "I-MISC",  # Miscellaneous entity
#     "B-PER",   # Beginning of a person's name right after another person's name
#     "I-PER",   # Person's name
#     "B-ORG",   # Beginning of an organisation right after another organisation
#     "I-ORG",   # Organisation
#     "B-LOC",   # Beginning of a location right after another location
#     "I-LOC"    # Location
# ]

In [3]:
# tạo label list tương ứng với bộ dữ liệu
label_list = [
    "B-CDT",
    "B-DA",
    "I-CDT",
    "I-DA",
    "O"

]

In [4]:
txt_file = '/home/phamson/data/real estate news/1.txt'

with open(txt_file, 'r') as file:
    for line in file:
        sentences = annotator.tokenize(line)
        for sentence in sentences:
            sequence = " ".join(sentence)  # tạo câu mới đã được tokenized 

            input_ids = torch.tensor([tokenizer.encode(sequence)])  # lấy id của các tokens tương ứng 
            # không dùng tokenize(decode(encode)), text sẽ bị lỗi khi tokenize do conflict với tokenizer mặc định
            tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(sequence))  # lấy các token để đánh tags 

            outputs = phobert_ner(input_ids).logits
            predictions = torch.argmax(outputs, dim=2)
            print(predictions)


            for i in [(token, label_list[prediction]) for token, prediction in zip(tokens, predictions[0].numpy())]:
                print(i)
            print('---------------------------------------------')        

tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('Lo_ngại', 'O')
('bong_bóng', 'O')
('bất_động_sản', 'O')
('(', 'O')
('BĐS', 'O')
(')', 'O')
('được', 'O')
('các', 'O')
('chuyên_gia', 'O')
('cho', 'O')
('rằng', 'O')
('chưa', 'O')
('đủ', 'O')
('cơ_sở', 'O')
('khi', 'O')
('thị_trường', 'O')
('đang', 'O')
('có', 'O')
('nhiều', 'O')
('lực', 'O')
('hỗ_trợ', 'O')
('.', 'O')
('</s>', 'O')
---------------------------------------------
tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('Dự_báo', 'O')
('các', 'O')
('phân', 'O')
('khúc', 'O')
('bất_động_sản', 'O')
('phục_vụ', 'O')
('nhu_cầu', 'O')
('thực', 'O')
('như', 'O')
('chung_cư', 'O')
(',', 'O')
('nhà', 'O')
('liền', 'O')
('thổ', 'O')
('...', 'O')
('vẫn', 'O')
('phát_triển', 'O')
('tốt', 'O')
('.', 'O')
('</s>', 'O')
---------------------------------------------
tensor([[4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('Thị_trường', 'O')
('BĐS', 'O')
('chưa', 'O')
('lo

tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('Nguyên_nhân', 'O')
('là', 'O')
('vì', 'O')
(',', 'O')
('nguồn', 'O')
('cung', 'O')
('sản_phẩm', 'O')
('nhà', 'O')
('liền', 'O')
('thổ', 'O')
(',', 'O')
('đặc_biệt', 'O')
('là', 'O')
('nhà', 'O')
('phố', 'O')
('thương_mại', 'O')
('ngày_càng', 'O')
('khan_hiếm', 'O')
(',', 'O')
('trong', 'O')
('khi', 'O')
('đây', 'O')
('là', 'O')
('tài_sản', 'O')
('có', 'O')
('giá_trị', 'O')
('sinh', 'O')
('lời', 'O')
('tốt', 'O')
('trong', 'O')
('trung', 'O')
('và', 'O')
('dài_hạn', 'O')
('nhờ', 'O')
('tích_hợp', 'O')
('cả', 'O')
('chức_năng', 'O')
('ở', 'O')
('kết_hợp', 'O')
('kinh_doanh', 'O')
(',', 'O')
('cho', 'O')
('thuê', 'O')
('.', 'O')
('</s>', 'O')
---------------------------------------------
tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('Ôn

tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('-', 'O')
('Hỗ_trợ', 'O')
('lãi', 'O')
('vay', 'O')
('tối_đa', 'O')
('8%', 'O')
('(', 'O')
('mức', 'O')
('vay', 'O')
('tối_đa', 'O')
('65%', 'O')
('giá_trị', 'O')
('hợp_đồng', 'O')
(')', 'O')
('</s>', 'O')
---------------------------------------------
tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('(', 'O')
('*', 'O')
(')', 'O')
('Chương_trình', 'O')
('áp_dụng', 'O')
('riêng', 'O')
('cho', 'O')
('từng', 'O')
('nhóm', 'O')
('sản_phẩm', 'O')
(',', 'O')
('không', 'O')
('áp_dụng', 'O')
('đồng_thời', 'O')
('tất_cả', 'O')
('các', 'O')
('chương_trình', 'O')
('cho', 'O')
('cùng', 'O')
('01', 'O')
('sản_phẩm', 'O')
('.', 'O')
('</s>', 'O')
---------------------------------------------
tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
('<s>', 'O')
('Chi_tiết', 'O')
('thể_lệ', 'O')
('chương_trình', 'O')
(':', 'O')
('TẠI', 'O')
('ĐÂY', 'O')
('hoặc', 'O'

In [5]:
# text = "Ngày 27/4, UBND TPHCM tổ chức lễ công bố quyết định của Thủ tướng Chính phủ công nhận huyện Cần Giờ đạt chuẩn nông thôn mới năm 2020 và công nhận xã đảo Thạnh An là xã đảo thuộc TPHCM."

# text = "Chủ tịch UBND TPHCM Nguyễn Thành Phong nhấn mạnh: đây là sự kiện quan trọng đánh dấu bước phát triển mới của huyện Cần Giờ, mở ra nhiều cơ hội để thúc đẩy phát triển kinh tế trong thời gian tới."

# text = "Thạnh An là xã đảo của huyện cần Giờ cách trung tâm huyện khoảng 8km tính theo đường chim bay và cách trung tâm TPHCM khoảng 50 km. Tổng diện tích tự nhiên cùa xã là 13.130 ha, chiếm 18,6% diện tích tự nhiên cùa huyện (ảnh: Trung Kiên)."

# text = 'Đặc biệt, với việc công nhận Thạnh An là xã đảo, người dân Thạnh An sẽ được hưởng nhiều cơ chế chính sách hơn cũng như các điều kiện thuận lợi để thúc đẩy phát triển kinh tế và nhanh chóng bắt kịp các xã khác của huyện Cần Giờ.'
#
# "Cuối năm 2020, thành phố vui mừng đón nhận Cù lao Gò Gia được Chính phủ công nhận thuộc TPHCM sau hơn 40 năm chồng lấn địa giới hành chính với tỉnh Đồng Nai. Và nay, Thủ tướng Chính phủ công nhận huyện Cần Giờ đạt chuẩn nông thôn mới năm 2020 và công nhận xã Thạnh An là xã đảo thuộc TPHCM", Chủ tịch UBND TPHCM bày tỏ.\
# Theo người đứng đầu chính quyền thành phố, con đường phía trước của Cần Giờ đang mở ra với nhiều cơ hội và thách thức đan xen, đòi hỏi Đảng bộ, Chính quyền và Nhân dân huyện Cần Giờ phải chủ động, sáng tạo, quyết liệt và nỗ lực không ngừng vươn lên.'
# text = "Đặc_biệt , với việc công_nhận Thạnh_An là xã đảo , người_dân Thạnh_An sẽ được hưởng nhiều cơ_chế chính_sách hơn cũng như các điều_kiện thuận_lợi để thúc_đẩy phát_triển kinh_tế và nhanh_chóng bắt kịp các xã khác của huyện Cần_Giờ ."

# text = 'Đặc biệt, với việc công nhận Thạnh An là xã đảo, người dân Thạnh An sẽ được hưởng nhiều cơ chế chính sách hơn cũng như các điều kiện thuận lợi để thúc đẩy phát triển kinh tế và nhanh chóng bắt kịp các xã khác của huyện Cần Giờ.'
# text = "Ngày 27/4, UBND TPHCM tổ chức lễ công bố quyết định của Thủ tướng Chính phủ công nhận huyện Cần Giờ đạt chuẩn nông thôn mới năm 2020 và công nhận xã đảo Thạnh An là xã đảo thuộc TPHCM."
# text = "Chủ tịch UBND TPHCM Nguyễn Thành Phong nhấn mạnh: đây là sự kiện quan trọng đánh dấu bước phát triển mới của huyện Cần Giờ, mở ra nhiều cơ hội để thúc đẩy phát triển kinh tế trong thời gian tới."

# text = "dự án Sun Grand City New An Thới với chủ đầu tư là công ty Sungroup"
# text = "Sun Grand City New An Thới nằm tiếp giáp đường 975 tuyến giao thông huyết mạch nối liền sân bay Phú Quốc, thị trấn An Thới, đường Nguyễn Văn Cừ, đây cũng là tuyến đường trung tâm kết nối mọi dự án của tập đoàn Sun Group tại đảo Ngọc."
# text = "Thông tin mô tả\
# Bán đất chính chủ, sổ đỏ đầy đủ, đường 24m, khu đô thị Hà Phong, Tiền Phong, Mê Linh, Hà Nội.\
# Diện tích 160m2, giá 50 triệu/m², có thương lượng.\
# Khu Đô Thị mới Hà Phong thuộc quần thể ĐTM Bắc Thăng Long, dự án được quy hoạch đạt tiêu chuẩn của KĐT hiện đại với kết cấu hạ tầng tiên tiến và hoàn chỉnh.\
# Từ vị trí KĐT đi vào trung tâm TP Hà Nội rất thuận tiện, chỉ mất 15 phút chạy xe."

# text = 'Độc quyền suất ngoại giao trực tiếp CĐT: Giá chỉ 25,6tr/m2.\
# TSG Lotus Long Biên: "Mua nhà ở ngay - nhận ngay sổ hồng".\
# * Trả trước chỉ 30% được nhận nhà ở ngay.\
# * Hỗ trợ vay vốn tới 70%GTCH trong 25 năm.\
# * Nhận Sổ ngay sau 45 ngày kể từ khi ký HĐ.\
# * Miễn phí sử dụng dịch vụ đến tháng 10/2021.'

# text = "Ban quản lý dự án Vinhomes Ocean Park kính gửi tới quý khách hàng danh sách biệt thự Shophouse bán mới nhất\
# Cập nhật danh sách Biệt thự shophouse bán tuần 2 tháng 4 đầy đủ nhất, giá tốt nhất thị trường.\
# Tổng hợp biệt thự Hải Âu và San Hô. "

text = "Thông tin chung cư Vinhomes Ocean Park Gia Lâm\
Vinhomes Ocean Park Gia Lâm được quy hoạch theo mô hình đô thị Singapore, mang đến cho cư dân một môi trường sống lý tưởng cùng nhiều tiện ích hấp dẫn như công viên thể thao ngoài trời, công viên BBQ... Với giải pháp tài chính linh hoạt, dự án hứa hẹn sẽ là giải pháp đột phá về nhà ở cho người dân và là cơ hội đầu tư đầy tiềm năng.\
- Tên dự án: Vinhomes Ocean Park (Gia Lâm)\
- Chủ đầu tư: Công TNHH Đầu tư và Phát triển đô thị Gia Lâm\
- Nhà thầu thi công: Công ty CP Xây dựng Coteccons\
- Vị trí: Xã Đa Tốn - Kiêu Kỵ - Dương Xá và một phần thị trấn Trâu Qùy, huyện Gia Lâm, TP. Hà Nội\
- Tổng diện tích: Khoảng 420ha\
- Mật độ xây dựng: 19,2%\
- Diện tích công viên, cây xanh: 62ha\
- Diện tích hồ điều hòa: 24,5ha\
- Biển hồ nước mặn: 6,1ha\
- Quy mô: 2 phân khu gồm phân khu cao tầng và phân khu thấp tầng\
- Phân khu thấp tầng: gồm 2.300 căn biệt thự với các loại hình\
+ Biệt thự nhà vườn: 168m2\
+ Biệt thự liền kề: 90-130m2\
+ Biệt thự đơn lập: 250-450m2\
+ Biệt thự song lập: 180-250m2\
+ Shophouse: 170-300m2\
- Phân khu cao tầng: gồm 4 tiểu khu (The Park, The River, The Sea, The Lake) với 66 tòa cao 23-26 tầng, các căn hộ có diện tích 35-85m2, từ 1-3 phòng ngủ"

# text = "thành phố Hà Nội"

text = "u hướng vì sức khoẻ ở phân khúc nhà hạng sang\nThứ tư, 4/3/2020, 08:00 (GMT+7) \nSunshine Group đầu tư nghìn tỷ cho tòa Aqua Beauty Resort nhằm đáp ứng nhu cầu căn hộ nghỉ dưỡng giới nhà giàu trong bối cảnh môi trường ngày càng ô nhiễm.\n\n\nCuối năm ngoái, Sunshine Group tung ra thị trường tổ hợp tổ hợp resort Sunshine Diamond River nằm trên đường Đào Trí, quận 7 giáp siêu dự án 6 tỷ USD Peninsula. Aqua Beauty Resort là một trong 8 tòa tháp của dự án 1,2 tỷ USD này.\n\nChủ đầu tư không giấu tham vọng biến hạng mục trở thành trung tâm làm đẹp, trị liệu hàng đầu tại Việt Nam. Tòa tháp được thiết kế cảnh quan như một resort tại Bali với không gian cây xanh mặt nước bố trí tận thềm căn hộ. Chủ đầu tư chi cả nghìn tỷ đồng chỉ phát triển hàng trăm tiện ích resort cho toà tháp như: dòng sông nhân tạo dài gần 1.000m hồ chân mây, hơn 40 khu vườn nhiệt đới, hàng chục vườn thiền, hàng chục hồ bơi trên cao, 4.000 vườn nhiệt đới mini trên không, quảng trường ánh sáng, sân trượt băng, khu phố mua sắm trong công viên, chuỗi Bungalow nghỉ dưỡng trên mặt nước.\n\n\n\n\nPhối cảnh dòng sông nhân tạo dài gần 1.000m của Aqua Beauty Resort nhìn từ trên cao.\n\n\nKhách hàng của sản phẩm là giới siêu giàu. Những cư dân thành thị không thể mua cây trồng khắp thành phố, nhưng có thể trồng rất nhiều cây trong khuôn viên dự án chính họ làm ra. \"Tôi không thể bảo vệ cư dân khỏi ô nhiễm ngoài đường, nhưng về nhà, họ sẽ tăng cường sức khỏe qua các tiện ích. Cư dân không có điều kiện du lịch thường xuyên, tôi sẽ khiến nơi ở của họ giống như resort\", vị đại diện chủ đầu tư chia sẻ về lý do Sunshine theo đuổi dòng căn hộ chăm sóc sức khỏe - wellness.\n\nNgoài ra, Sunshine Group đầu tư gần 20 tiện ích chuyên phục vụ trị liệu, nghỉ dưỡng, làm đẹp và thanh lọc cơ thể tại tòa tháp. Trong đó, một khu đại spa hiện đại và quy mô rộng hàng nghìn m2 bố trí tại tầng đế của tòa tháp, với 4 phân khu: aqua spa, formal spa, detox center cùng hệ thống vườn trị liệu. Bên cạnh công nghệ làm đẹp, tòa tháp sở hữu trung tâm thanh lọc cơ thể (detox) quy mô lớn, bao gồm: chuỗi phòng detox thuỷ liệu, quang học và khí detox; chuỗi nhà hàng và cửa hàng chuyên bán và cung cấp các liệu trình detox cho cư dân, trung tâm khí liệu chuyên dạy yoga và phương pháp dưỡng sinh.\n\nThực tế Aqua Beauty Resort là sản phẩm tiếp nối mô hình \"wellness\" trong lĩnh địa ốc tại Việt Nam thời gian qua. Theo giới đầu tư, khái niệm wellness gắn với các không gian sống và làm việc được thiết kế với mục tiêu chú trọng vào sức khỏe thể chất và tinh thần.\n\nManh nha từ một tổ hợp dự án nghỉ dưỡng tại Đà Nẵng hồi những năm 2016-2017, đến 2018 với mô hình này bùng nổ khi lan nhanh sang đến dự án căn hộ cao cấp tại các đô thị lớn. Diamond Island của Kusto Home, The Vista Verde của Capitaland tại khu Đông, Green Star Sky Garden (Hưng Lộc Phát)... những dự án đóng góp cho sự sôi động của phân khúc này trên thị trường TP HCM. Tại Hà Nội, Ecopark Grand - The Island của Tập đoàn Ecopark lại tận dụng lợi thế thiên nhiên sẵn có để tạo dựng một không gian sống đúng chuẩn wellness.\n\nTheo báo cáo Build Well to Live Well, thị trường bất động sản tích hợp các tiện ích hướng đến mục tiêu chăm sóc sức khoẻ (wellness real estate) trên thế giới hiện có giá trị 134 tỷ USD và ước tính sẽ tăng lên 180 tỷ USD vào năm 2022, chiếm khoảng 50% so với ngành công nghiệp xây dựng \"xanh\" trên toàn cầu.\n\nMột báo cáo từ Savills cũng đánh giá sản phẩm \"wellness\" là xu hướng mới trong thị trường bất động sản nghỉ dưỡng toàn cầu với sự xuất hiện của các wellness resort, spa resort. Và tại Việt Nam, mô hình này còn rất mới.\n\n\n\n\nPhối cảnh Detox Center quy mô lớn trong lòng dự án.\n\n\nTiến sĩ Trần Nguyễn Minh Hải - chuyên gia địa ốc Đại học Ngân hàng TP HCM cho rằng thị trường địa ốc đang theo xu hướng phát triển bền vững. Yếu tố khỏe sẽ là tiêu chí ưu tiên khi chọn sản phẩm. Do đó, mô hình căn hộ hướng đến sức khỏe (wellness real estate) đòi hỏi tiềm lực tài chính của mỗi chủ đầu tư. Khi người dân có nhu cầu, thị trường sẽ phải chuyển dịch. \"Đây được xem như tiêu chí quan trọng quyết định việc xuống tiền của nhóm khách hàng trung và thượng lưu\", vị chuyên gia nói.\n\nQuang Minh, một nhà đầu tư tại quận 8, TP HCM, cho rằng xu hướng \"wellness\" nâng tầm giá trị cho mỗi căn hộ và là sản phẩm có tiềm năng đầu tư trong tương lai bởi bắt trúng nhu cầu của những người giàu có.\n\nThanh Hương"



sentences = annotator.tokenize(text)

for sentence in sentences:
    sequence = " ".join(sentence)  # tạo câu mới đã được tokenized 

    input_ids = torch.tensor([tokenizer.encode(sequence)])  # lấy id của các tokens tương ứng 
    # không dùng tokenize(decode(encode)), text sẽ bị lỗi khi tokenize do conflict với tokenizer mặc định
    tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(sequence))  # lấy các token để đánh tags 
    
    outputs = phobert_ner(input_ids).logits
    predictions = torch.argmax(outputs, dim=2)
    
    
    for i in [(token, label_list[prediction]) for token, prediction in zip(tokens, predictions[0].numpy())]:
        print(i)
    print('---------------------------------------------')
    

('<s>', 'O')
('u', 'O')
('hướng', 'O')
('vì', 'O')
('sức_khoẻ', 'O')
('ở', 'O')
('phân', 'O')
('khúc', 'O')
('nhà', 'O')
('hạng', 'O')
('sang', 'O')
('Thứ', 'O')
('tư', 'O')
(',', 'O')
('4/@@', 'O')
('3/@@', 'O')
('2020', 'O')
(',', 'O')
('08:00', 'O')
('(', 'O')
('GMT', 'O')
('+@@', 'O')
('7', 'O')
(')', 'O')
('Sunsh@@', 'O')
('ine_@@', 'O')
('Group', 'O')
('đầu_tư', 'O')
('nghìn', 'O')
('tỷ', 'O')
('cho', 'O')
('toà', 'O')
('A@@', 'O')
('qua_@@', 'O')
('Beauty_@@', 'O')
('Resort', 'O')
('nhằm', 'O')
('đáp_ứng', 'O')
('nhu_cầu', 'O')
('căn_hộ', 'O')
('nghỉ_dưỡng', 'O')
('giới', 'O')
('nhà', 'O')
('giàu', 'O')
('trong', 'O')
('bối_cảnh', 'O')
('môi_trường', 'O')
('ngày_càng', 'O')
('ô_nhiễm', 'O')
('.', 'O')
('</s>', 'O')
---------------------------------------------
('<s>', 'O')
('Cuối', 'O')
('năm_ngoái', 'O')
(',', 'O')
('Sunsh@@', 'O')
('ine_@@', 'O')
('Group', 'O')
('tung', 'O')
('ra', 'O')
('thị_trường', 'O')
('tổ_hợp', 'O')
('tổ_hợp', 'O')
('resort', 'O')
('Sunsh@@', 'O')
('ine_

('<s>', 'O')
('Tại', 'O')
('Hà_Nội', 'O')
(',', 'O')
('Eco@@', 'O')
('par@@', 'O')
('k_@@', 'O')
('Grand', 'O')
('-', 'O')
('The_@@', 'O')
('Island', 'O')
('của', 'O')
('Tập_đoàn', 'O')
('Ecopark', 'O')
('lại', 'O')
('tận_dụng', 'O')
('lợi_thế', 'O')
('thiên_nhiên', 'O')
('sẵn', 'O')
('có', 'O')
('để', 'O')
('tạo_dựng', 'O')
('một', 'O')
('không_gian', 'O')
('sống', 'O')
('đúng', 'O')
('chuẩn', 'O')
('well@@', 'O')
('ness', 'O')
('.', 'O')
('</s>', 'O')
---------------------------------------------
('<s>', 'O')
('Theo', 'O')
('báo_cáo', 'O')
('Bu@@', 'O')
('il@@', 'O')
('d_@@', 'O')
('W@@', 'O')
('ell', 'O')
('to', 'O')
('Live_@@', 'O')
('W@@', 'O')
('ell', 'O')
(',', 'O')
('thị_trường', 'O')
('bất_động_sản', 'O')
('tích_hợp', 'O')
('các', 'O')
('tiện_ích', 'O')
('hướng', 'O')
('đến', 'O')
('mục_tiêu', 'O')
('chăm_sóc', 'O')
('sức_khoẻ', 'O')
('(', 'O')
('well@@', 'O')
('ness', 'O')
('real', 'O')
('est@@', 'O')
('ate', 'O')
(')', 'O')
('trên', 'O')
('thế_giới', 'O')
('hiện', 'O')
('có'

In [161]:
# VncoreNLP 
ner = annotator.ner(text)

ner

[[('Độc_quyền', 'O'),
  ('suất', 'O'),
  ('ngoại_giao', 'O'),
  ('trực_tiếp', 'O'),
  ('CĐT', 'O'),
  (':', 'O'),
  ('Giá', 'O'),
  ('chỉ', 'O'),
  ('25,6', 'O'),
  ('tr', 'O'),
  ('/', 'O'),
  ('m2', 'O'),
  ('.', 'O')],
 [('TSG', 'O'),
  ('Lotus_Long_Biên', 'B-PER'),
  (':', 'O'),
  ('"', 'O'),
  ('Mua', 'O'),
  ('nhà', 'O'),
  ('ở', 'O'),
  ('ngay', 'O'),
  ('-', 'O'),
  ('nhận', 'O'),
  ('ngay', 'O'),
  ('sổ', 'O'),
  ('hồng', 'O'),
  ('"', 'O'),
  ('.', 'O')],
 [('*', 'O'),
  ('Trả', 'O'),
  ('trước', 'O'),
  ('chỉ', 'O'),
  ('30%', 'O'),
  ('được', 'O'),
  ('nhận', 'O'),
  ('nhà', 'O'),
  ('ở', 'O'),
  ('ngay', 'O'),
  ('.', 'O')],
 [('*', 'O'),
  ('Hỗ_trợ', 'O'),
  ('vay', 'O'),
  ('vốn', 'O'),
  ('tới', 'O'),
  ('70%', 'O'),
  ('GTCH', 'O'),
  ('trong', 'O'),
  ('25', 'O'),
  ('năm', 'O'),
  ('.', 'O')],
 [('*', 'O'),
  ('Nhận_Sổ', 'O'),
  ('ngay', 'O'),
  ('sau', 'O'),
  ('45', 'O'),
  ('ngày', 'O'),
  ('kể', 'O'),
  ('từ', 'O'),
  ('khi', 'O'),
  ('ký', 'O'),
  ('HĐ', 'O'),
 